#This bar will be displayed if there are active boosters
bar-pattern: "&b%minecraft%x &aEXP &7| &b%mcmmo%x &aMcMMO &7| &b%jobs_xp%x &aJob &7| &b%jobs_money%x &e$ &7[&f%duration% m&7]"

#This message will be displayed above the bar if the empty bar option is set to true
default-bar-message: "&c&lNo active boosters"

#Set this option to true to display the default message in the bar when there is no active booster
#Otherwise the bar will disappear
empty-bar: true

#Choose a storage system here
#mysql or yaml
storage-system: yaml

#How often the plugin should save players (time in seconds)
saving-time: 600

mysql:
  host: "localhost"
  port: 3306
  database: Boosters
  username: "root"
  password: ""

boosters:
  #This is an example booster
  example_booster:
    #Choose the type among jobs_xp, jobs_money, mcmmo and minecraft
    type: jobs_money
    #Choose a multiplier
    multiplier: 2
    #Choose a duration (seconds)
    duration: 60