---
#---------------------------------------------------------------#
#   __________________                       __                 #
#  /  _____/\______   \ ____   ____  _______/  |_  ___________  #
# /   \  ___ |    |  _//  _ \ /  _ \/  ___/\   __\/ __ \_  __ \ #
# \    \_\  \|    |   (  <_> |  <_> )___ \  |  | \  ___/|  | \/ #
#  \______  /|______  /\____/ \____/____  > |__|  \___  >__|    #
#         \/        \/                  \/            \/        #
#---------------------------------------------------------------#

# This bar will be displayed in order when boosters are active
# To not display anything for specified values set them to: ""
# Set every value to "" to disable the bar.
bar-pattern:
  minecraft: "&a%minecraft%% &fExp"
  mcmmo: "&a%mcmmo%% &fMcMMO"
  jobs-xp: "&a%jobs_xp%% &fJob"
  jobs-money: "&a%jobs_money%% &e$"
  duration: " &7[&f%duration% min&7]"
  separator: " &8&mo&r "

# Choose a storage system (mysql or yaml)
storage-system: yaml

# How often the plugin should save players (time in seconds)
saving-time: 600

mysql:
  host: "localhost"
  port: 3306
  database: gbooster
  username: "gbooster"
  password: ""
  prefix: "server_"
  # prefix: "" # Use for no prefix

boosters:
  jobs_xp_2:
    # Choose from jobs_xp, jobs_money, mcmmo and minecraft
    type: jobs_xp
    # Choose a multiplier (only numbers from 1-8 -> +20% would be 1.2)
    multiplier: 2
    # Choose a duration (seconds)
    duration: 3600
  jobs_money_2:
    type: jobs_money
    multiplier: 2
    duration: 3600
  mcmmo_xp_2:
    type: mcmmo
    multiplier: 2
    duration: 3600
  minecraft_xp_2:
    type: minecraft
    # Don't use floating-point numbers for type minecraft!
    multiplier: 2
    duration: 3600
