name: GBooster
version: 1.0.1
main: com.tamrielnetwork.gbooster.gbooster.GBooster
api-version: 1.16
authors: [Manu,TamrielNetwork]
depend: [PlaceholderAPI, Jobs]
commands:
  gbooster:
    description: "Main command"
    usage: "/gbooster give <player> <boosterid> <amount> | /gbooster use <boosterid>"
permissions:
  gbooster.give:
    description: "Permission to give boosters"
    default: op
