name: GBooster
version: @version@
main: com.tamrielnetwork.gbooster.gbooster.GBooster
api-version: 1.16
authors: [Manu,TamrielNetwork]
website: https://tamriel.site
description: Provides Global Boosters for JobsReborn, McMMO and Minecraft.
depend: [PlaceholderAPI, Jobs]
commands:
  gbooster:
    description: "Main command"
    usage: "/gbooster give <player> <boosterid> <amount> | /gbooster use <boosterid>"
permissions:
  gbooster.give:
    description: "Permission to give boosters"
    default: op
