name: GBooster
version: @version@
main: dev.meinel.leo.gbooster.GBooster
api-version: 1.17
authors: [ Manu,Leopold Meinel ]
description: Provides Global Boosters for JobsReborn, McMMO and Minecraft.
depend: [ PlaceholderAPI ]
softdepend: [ Jobs, McMMO ]
commands:
  gbooster:
    description: "Main command"
    usage: "/gbooster give <player> <boosterid> <amount> | /gbooster use <boosterid> | /gbooster time"
permissions:
  gbooster.give:
    description: "Permission to give boosters"
    default: op
  gbooster.use:
    description: "Use boosters"
    default: op
  gbooster.time:
    description: "Shows time of booster that ends next"
    default: op
