name: GBooster
version: @version@
main: dev.meinel.leo.gbooster.GBooster
api-version: 1.17
authors: [ Manu,Leopold Meinel ]
description: Provides Global Boosters for JobsReborn, McMMO and Minecraft.
depend: [ PlaceholderAPI ]
softdepend: [ Jobs, McMMO ]
commands:
  gbooster:
    description: "Main command"
    usage: "/gbooster give <player> <boosterid> <amount> | /gbooster use <boosterid> | /gbooster time"
permissions:
  gbooster.list:
    description: "List boosters"
    default: op
  gbooster.give:
    description: "Give boosters"
    default: op
  gbooster.take:
    description: "Take boosters"
    default: op
  gbooster.time:
    description: "Show time of booster that ends next"
    default: op
  gbooster.use:
    description: "Use boosters"
    default: op
